espn_api_base: "https://site.api.espn.com/apis/site/v2"
weights:
  season_avg_margin: 0.55     # Tuned: season-heavy performed best in sweep
  rolling_avg_margin: 0.20    # Tuned: reduced recency weight
  sos: 0.20                   # Maintain - strength of schedule matters  
  recency_factor: 0.05        # Light recency factor
output_dir: "./output"
logging:
  level: "INFO"
